# Site settings
title: Rui Wang's Blog
email: harry.r.wang@gmail.com
author: Rui Wang
description: "Hi there, I am Rui Wang. A software developer from Cambridge UK. I write about software development and architecture."
baseurl: ""
url: "http://ruiwanguk.github.com"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
